# Cryptostore sample config file for Docker

cache: redis

redis:
    ip: redisdb
    port: 6379
    del_after_read: true
    start_flush: true
    socket: null

storage: [influx]

influx:
    addr: "<InfluxDB URL>"
    org: "<ORGANIZATION>"
    bucket: "<BUCKET_NAME>"
    token: "<InfluxDB TOKEN>"
    precision: ns

storage_interval: 0.1
    

exchanges:
    BINANCE:
        l2_book:
            symbols:
                [
                    BTC-USDT,
                    ETH-USDT,
                    ETC-USDT,
                    XRP-USDT,
                    BCH-USDT,
                    LTC-USDT,
                    EOS-USDT,
                    XMR-USDT,
                    DASH-USDT,
                    TRX-USDT,
                    XTZ-USDT,
                    QTUM-USDT,
                    OMG-USDT,
                ]
            book_delta: true
        trades:
            [
                BTC-USDT,
                ETH-USDT,
                ETC-USDT,
                XRP-USDT,
                BCH-USDT,
                LTC-USDT,
                EOS-USDT,
                XMR-USDT,
                DASH-USDT,
                TRX-USDT,
                XTZ-USDT,
                QTUM-USDT,
                OMG-USDT,
            ]
    BINANCE_US:
        l2_book:
            symbols:
                [
                    BTC-USDT,
                    ETH-USDT,
                    ETC-USDT,
                    XRP-USDT,
                    BCH-USDT,
                    LTC-USDT,
                    QTUM-USDT,
                ]
            book_delta: true
        trades:
            [
                BTC-USDT,
                ETH-USDT,
                ETC-USDT,
                XRP-USDT,
                BCH-USDT,
                LTC-USDT,
                QTUM-USDT,
            ]
    BITFINEX:
        l2_book:
            symbols:
                [
                    BTC-USD,
                    ETH-USD,
                    ETC-USD,
                    XRP-USD,
                    BSV-USD,
                    LTC-USD,
                    EOS-USD,
                    XMR-USD,
                    XLM-USD,
                    TRX-USD,
                    XTZ-USD,
                    OMG-USD,
                ]
            book_delta: true
        trades:
            [
                BTC-USD,
                ETH-USD,
                ETC-USD,
                XRP-USD,
                BSV-USD,
                LTC-USD,
                EOS-USD,
                XMR-USD,
                XLM-USD,
                TRX-USD,
                XTZ-USD,
                OMG-USD,
            ]
    UPBIT:
        trades:
            [
                "BTC-KRW",
                "ETH-KRW",
                "ETH-BTC",
                "LTC-BTC",
                "STRAT-BTC",
                "XRP-BTC",
                "ETC-BTC",
                "OMG-BTC",
                "CVC-BTC",
                "DGB-BTC",
                "PAY-BTC",
                "SC-BTC",
                "SNT-BTC",
                "XVG-BTC",
                "WAVES-BTC",
                "NMR-BTC",
                "GBYTE-BTC",
                "XEM-BTC",
                "LBC-BTC",
                "QTUM-BTC",
                "GNT-BTC",
                "NXT-BTC",
                "BAT-BTC",
                "XEL-BTC",
                "LSK-BTC",
                "RDD-BTC",
                "DCT-BTC",
                "STEEM-BTC",
                "FCT-BTC",
                "DCR-BTC",
                "DOGE-BTC",
                "BNT-BTC",
                "XLM-BTC",
                "PART-BTC",
                "MCO-BTC",
                "UBQ-BTC",
                "ARDR-BTC",
                "KMD-BTC",
                "ARK-BTC",
                "ADX-BTC",
                "SYS-BTC",
                "ANT-BTC",
                "XDN-BTC",
                "STORJ-BTC",
                "QRL-BTC",
                "NXS-BTC",
                "GRS-BTC",
                "VTC-BTC",
                "SIB-BTC",
                "REP-BTC",
                "RLC-BTC",
                "BLOCK-BTC",
                "XZC-BTC",
                "ADT-BTC",
                "ION-BTC",
                "EMC2-BTC",
                "EXCL-BTC",
                "EXP-BTC",
                "BURST-BTC",
                "BLK-BTC",
                "ZEN-BTC",
                "RADS-BTC",
                "BTC-USDT",
                "ETH-USDT",
                "LTC-USDT",
                "XRP-USDT",
                "ETC-USDT",
                "NEO-KRW",
                "MTL-KRW",
                "LTC-KRW",
                "STRAT-KRW",
                "XRP-KRW",
                "ETC-KRW",
                "OMG-KRW",
                "SNT-KRW",
                "WAVES-KRW",
                "XEM-KRW",
                "QTUM-KRW",
                "GNT-KRW",
                "LSK-KRW",
                "STEEM-KRW",
                "XLM-KRW",
                "ARDR-KRW",
                "KMD-KRW",
                "ARK-KRW",
                "STORJ-KRW",
                "GRS-KRW",
                "VTC-KRW",
                "REP-KRW",
                "EMC2-KRW",
                "NAV-BTC",
                "ADA-KRW",
                "ADA-BTC",
                "MANA-BTC",
                "OMG-USDT",
                "SBD-KRW",
                "SBD-BTC",
                "RCN-BTC",
                "VIB-BTC",
                "POWR-KRW",
                "POWR-BTC",
                "BTG-KRW",
                "XVG-USDT",
                "ADA-USDT",
                "ENG-BTC",
                "UKG-BTC",
                "DNT-BTC",
                "IGNIS-BTC",
                "SRN-BTC",
                "ZRX-BTC",
                "VEE-BTC",
                "BCPT-BTC",
                "TRX-BTC",
                "TUSD-BTC",
                "LRC-BTC",
                "UP-BTC",
                "ICX-KRW",
                "EOS-KRW",
                "STORM-KRW",
                "DMT-BTC",
                "TUSD-USDT",
                "TRX-KRW",
                "POLY-BTC",
                "MCO-KRW",
                "PRO-BTC",
                "SC-USDT",
                "TRX-USDT",
                "SC-KRW",
                "GTO-KRW",
                "IGNIS-KRW",
                "ONT-KRW",
                "DCR-KRW",
                "ZIL-KRW",
                "BLT-BTC",
                "STORM-BTC",
                "AID-BTC",
                "GTO-BTC",
                "DCR-USDT",
                "POLY-KRW",
                "ZRX-KRW",
                "SRN-KRW",
                "LOOM-KRW",
                "CMCT-BTC",
                "BCH-BTC",
                "BCH-USDT",
                "BCH-KRW",
                "BKX-BTC",
                "MFT-BTC",
                "LOOM-BTC",
                "ADT-KRW",
                "ADX-KRW",
                "BAT-KRW",
                "IOST-KRW",
                "RFR-BTC",
                "DMT-KRW",
                "RFR-KRW",
                "DGB-USDT",
                "CVC-KRW",
                "IQ-KRW",
                "IOTA-KRW",
                "OST-KRW",
                "RVN-BTC",
                "BFT-BTC",
                "GO-BTC",
                "UPP-BTC",
                "ENJ-BTC",
                "MET-BTC",
                "HYDRO-BTC",
                "MFT-KRW",
                "CRW-BTC",
                "DTA-BTC",
                "EDR-BTC",
                "ONG-KRW",
                "GAS-KRW",
                "MTL-BTC",
                "UPP-KRW",
                "ELF-KRW",
                "PMA-BTC",
                "DOGE-USDT",
                "ZRX-USDT",
                "RVN-USDT",
                "BAT-USDT",
                "KNC-KRW",
                "PAL-BTC",
                "PAX-BTC",
                "MOC-BTC",
                "NPXS-BTC",
                "ZIL-BTC",
                "OST-BTC",
                "SPC-BTC",
                "BSV-KRW",
                "BSV-BTC",
                "IOST-BTC",
                "XNK-BTC",
                "THETA-KRW",
                "NCASH-BTC",
                "JNT-BTC",
                "LBA-BTC",
                "EDR-KRW",
                "DENT-BTC",
                "QKC-KRW",
                "BTM-BTC",
                "ELF-BTC",
                "BTT-KRW",
                "BTT-BTC",
                "VITE-BTC",
                "IOTX-BTC",
                "BTU-BTC",
                "SOLVE-BTC",
                "NKN-BTC",
                "QNT-BTC",
                "CTXC-BTC",
                "SPND-BTC",
                "META-BTC",
                "MOC-KRW",
                "SERV-BTC",
                "ANKR-BTC",
                "COSM-KRW",
                "CRO-BTC",
                "ENJ-KRW",
                "TFUEL-KRW",
                "BTS-BTC",
                "FSN-BTC",
                "MANA-KRW",
                "TTC-BTC",
                "ANKR-KRW",
                "VBK-BTC",
                "ORBS-BTC",
                "NPXS-KRW",
                "AERGO-BTC",
                "TTC-KRW",
                "PI-BTC",
                "AERGO-KRW",
                "ATOM-KRW",
                "TT-KRW",
                "CRE-KRW",
                "VDX-BTC",
                "SOLVE-KRW",
                "COSM-BTC",
                "ATOM-BTC",
                "STPT-BTC",
                "MBL-KRW",
                "LAMB-BTC",
                "EOS-BTC",
                "LUNA-BTC",
                "DAI-BTC",
                "MKR-BTC",
                "BORA-BTC",
                "TSHP-KRW",
                "TSHP-BTC",
                "WAXP-KRW",
                "WAXP-BTC",
                "HBAR-KRW",
                "MED-KRW",
                "MED-BTC",
                "MLK-BTC",
                "MLK-KRW",
                "PXL-BTC",
            ]



