# Cryptostore sample config file for Docker

cache: redis

redis:
    ip: redisdb
    port: 6379
    del_after_read: true
    start_flush: true
    socket: null

storage: [influx]

influx:
    addr: "<InfluxDB URL>"
    org: "<ORGANIZATION>"
    bucket: "<BUCKET_NAME>"
    token: "<InfluxDB TOKEN>"
    precision: ns

storage_interval: 0.1

exchanges:
    BINANCE:
        l2_book:
            symbols:
                [
                    BTC-USDT,
                    ETH-USDT,
                    ETC-USDT,
                    XRP-USDT,
                    BCH-USDT,
                    LTC-USDT,
                    EOS-USDT,
                    XMR-USDT,
                    DASH-USDT,
                    TRX-USDT,
                    XTZ-USDT,
                    QTUM-USDT,
                    OMG-USDT,
                ]
            book_delta: true
        trades:
            [
                BTC-USDT,
                ETH-USDT,
                ETC-USDT,
                XRP-USDT,
                BCH-USDT,
                LTC-USDT,
                EOS-USDT,
                XMR-USDT,
                DASH-USDT,
                TRX-USDT,
                XTZ-USDT,
                QTUM-USDT,
                OMG-USDT,
            ]
    BINANCE_US:
        l2_book:
            symbols:
                [
                    BTC-USDT,
                    ETH-USDT,
                    ETC-USDT,
                    XRP-USDT,
                    BCH-USDT,
                    LTC-USDT,
                    QTUM-USDT,
                ]
            book_delta: true
        trades:
            [
                BTC-USDT,
                ETH-USDT,
                ETC-USDT,
                XRP-USDT,
                BCH-USDT,
                LTC-USDT,
                QTUM-USDT,
            ]
    BITFINEX:
        l2_book:
            symbols:
                [
                    BTC-USD,
                    ETH-USD,
                    ETC-USD,
                    XRP-USD,
                    BSV-USD,
                    LTC-USD,
                    EOS-USD,
                    XMR-USD,
                    XLM-USD,
                    TRX-USD,
                    XTZ-USD,
                    OMG-USD,
                ]
            book_delta: true
        trades:
            [
                BTC-USD,
                ETH-USD,
                ETC-USD,
                XRP-USD,
                BSV-USD,
                LTC-USD,
                EOS-USD,
                XMR-USD,
                XLM-USD,
                TRX-USD,
                XTZ-USD,
                OMG-USD,
            ]
    UPBIT:
        trades:
            [
                "BTC-KRW",
                "ETH-KRW",
                "NEO-KRW",
                "MTL-KRW",
                "LTC-KRW",
                "STRAT-KRW",
                "XRP-KRW",
                "ETC-KRW",
                "OMG-KRW",
                "SNT-KRW",
                "WAVES-KRW",
                "XEM-KRW",
                "QTUM-KRW",
                "GNT-KRW",
                "LSK-KRW",
                "STEEM-KRW",
                "XLM-KRW",
                "ARDR-KRW",
                "KMD-KRW",
                "ARK-KRW",
                "STORJ-KRW",
                "GRS-KRW",
                "VTC-KRW",
                "REP-KRW",
                "EMC2-KRW",
                "ADA-KRW",
                "SBD-KRW",
                "POWR-KRW",
                "BTG-KRW",
                "ICX-KRW",
                "EOS-KRW",
                "STORM-KRW",
                "TRX-KRW",
                "MCO-KRW",
                "SC-KRW",
                "GTO-KRW",
                "IGNIS-KRW",
                "ONT-KRW",
                "DCR-KRW",
                "ZIL-KRW",
                "POLY-KRW",
                "ZRX-KRW",
                "SRN-KRW",
                "LOOM-KRW",
                "BCH-KRW",
                "ADT-KRW",
                "ADX-KRW",
                "BAT-KRW",
                "IOST-KRW",
                "DMT-KRW",
                "RFR-KRW",
                "CVC-KRW",
                "IQ-KRW",
                "IOTA-KRW",
                "OST-KRW",
                "MFT-KRW",
                "ONG-KRW",
                "GAS-KRW",
                "UPP-KRW",
                "ELF-KRW",
                "KNC-KRW",
                "BSV-KRW",
                "THETA-KRW",
                "EDR-KRW",
                "QKC-KRW",
                "BTT-KRW",
                "MOC-KRW",
                "COSM-KRW",
                "ENJ-KRW",
                "TFUEL-KRW",
                "MANA-KRW",
                "ANKR-KRW",
                "NPXS-KRW",
                "TTC-KRW",
                "AERGO-KRW",
                "ATOM-KRW",
                "TT-KRW",
                "CRE-KRW",
                "SOLVE-KRW",
                "MBL-KRW",
                "TSHP-KRW",
                "WAXP-KRW",
                "HBAR-KRW",
                "MED-KRW",
                "MLK-KRW",
            ]
