version: "2.2"
services:
  cryptostore:
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    build:
      context: .
      dockerfile: Dockerfile
  redisdb:
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    image: redis:5.0.5
    expose:
      - 6379
    command: ["redis-server", "--maxmemory", "3gb", "--maxmemory-policy", "allkeys-lru", "--save", "''", "--appendonly", "no"]

